{% set name = "sierra" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sierra-{{ version }}.tar.gz
  sha256: 93aa9a59c5f9cc0b3ff32d8d2f40901b27d8001e073d0e63f26e5c2f1acde2e9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - beautifulsoup4
    - pandas
    - python >={{ python_min }}

test:
  imports:
    - sierra
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/BrainStormYourWayIn/sierra
  summary: Write HTML and CSS in pure Python using the DOM API
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://brainstormyourwayin.github.io/sierra.github.io/

extra:
  recipe-maintainers:
    - thewchan
